name: ischool

channels:
  - conda-forge

dependencies:
  # other packages
  - jupyter-rsession-proxy==2.2.1
  - traitlets==5.14.3
  - appmode==1.0.0

  - pip:
      # from infra-requirements
      - git+https://github.com/shaneknapp/python-popularity-contest.git@add-error-handling
